### ISSUE TITLE
Replicating ARIMA results

### ISSUE THREAD

**Issue by mloning** [Mcompetitions/M4-methods#24]
How were the ARIMA results generated? I can only find the submission file with the results, but not the code used to generate them. Was any preprocessing applied? Any non-default hyper-parameters settings? Did you use forecast's `auto.arima` (v8.2)?

**Comment by vangspiliot** [comment]
The ARIMA method was implemented using the auto.arima function from the forecast package, as noted here
https://www.sciencedirect.com/science/article/pii/S0169207019301128
No pre-processing took place and none of the hyper-parameters was manually set.
Any differences with the published results should be due to package updates.

**Comment by mloning** [comment]
Okay, thanks for the info, will look into it!

**Comment by mloning** [comment]
Have you published ARIMA results by category (yearly, quarterly, etc) somewhere?

**Comment by vangspiliot** [comment]
Yes. You may find them here
https://github.com/Mcompetitions/M4-methods/tree/master/Point%20Forecasts
labelled as "submission-ARIMA.rar"
